import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import { IProduct } from "../interfaces/IProduct";
import { ProductCollection } from "../components/ProductCollection";
import { Cart } from "../components/Cart";
import { useCart } from "../context/CartContextProvider";
import { FiShoppingCart } from "react-icons/fi";
import { ToastContainer } from "react-toastify";

import { SearchBar } from "@/components/SearchBar";

export default function Home() {
  const [products, setProducts] = useState<IProduct[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showCart, setShowCart] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const { addItem } = useCart();

  const handleSearch = async (term: string) => {
    setSearchTerm(term);
    const response = searchTerm
      ? await fetch(`/api/searchProducts/?search=${term}`)
      : await fetch("/api/products");
    const data = await response.json();
    setProducts(data.products);
    setIsLoading(false);
  };

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch("/api/products");
      const data = await response.json();
      setProducts(data.products);
      setIsLoading(false);
      console.log("sem term", data.products);
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-primary-blue fixed w-full z-50">
        <div className="flex gap-4 justify-center align-middle p-1">
          <div className="max-w-50 ">
            <SearchBar onSearch={handleSearch} products={products} />
          </div>
          <button
            onClick={() => setShowCart(true)}
            type="button"
            className="sm:hidden lg:block ml-3 h-20 w-20  flex items-center justify-center rounded-full"
          >
            <span className="sr-only">Carrinho</span>
            <FiShoppingCart className="color-red w-10 h-10" />
          </button>
        </div>
      </header>
      <main className={`${styles.main} sm:p-1`}>
        <div>
          <ToastContainer />
        </div>
        <div className="fixed bottom-0 right-0 mb-4 mr-4 z-50">
          <button
            onClick={() => setShowCart(true)}
            type="button"
            className="lg:hidden ml-3 h-20 w-20 bg-gray-100 flex items-center justify-center rounded-full border-2 border-opacity-80 border-primary-blue opacity-90"
          >
            <span className="sr-only">Carrinho</span>
            <FiShoppingCart className="w-10 h-10" />
          </button>
        </div>
        <div className=" sm:w-80 lg:w-1/2 ">
          {showCart && (
            <Cart open={showCart} onClose={() => setShowCart(false)} />
          )}
          {isLoading ? (
            <p>Carregando</p>
          ) : (
            <div>
              <ProductCollection products={products} onAddToCart={addItem} />
            </div>
          )}
        </div>
      </main>
    </>
  );
}
