import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useContext } from "react";
import { IProduct } from "../interfaces/IProduct";
import { ProductCollection } from "../components/ProductCollection";
import Cart from "../components/Cart";
import { useCart } from "../context/CartContextProvider";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  const [products, setProducts] = useState<IProduct[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showCart, setShowCart] = useState(true);

  const showToastMessage = () => {
    toast.success("Success Notification !", {
      position: toast.POSITION.TOP_RIGHT,
    });
  };

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch("/api/products");
      const data = await response.json();
      setProducts(data.products);
      setIsLoading(false);
    };
    fetchData();
  }, []);
  const { addItem } = useCart();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button onClick={showToastMessage}>Notify</button>
          <ToastContainer />
        </div>
        {/* <button onClick={() => setShowCart(true)}>Carrinho</button>
        {showCart && <Cart onClose={() => setShowCart(false)} />} */}
        <div>
          <button onClick={() => setShowCart(true)}>View Cart</button>
          {showCart && (
            <Cart open={showCart} onClose={() => setShowCart(false)} />
          )}
          <h1>Lista de produtos:</h1>
          {isLoading ? (
            <p>Carregando</p>
          ) : (
            <ProductCollection products={products} onAddToCart={addItem} />
            // <div className="bg-white font-sans">
            //   <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
            //     <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            //       Customers also purchased
            //     </h2>

            //     <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
            //       {Array.isArray(products) && products.length > 0 ? (
            //         products.map((product) => (
            //           <div key={product.ean} className="group relative">
            //             <div className="min-h-80 aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
            //               <Image
            //                 src={product.picture}
            //                 alt={product.fullname}
            //                 width="100"
            //                 height="100"
            //                 className="h-full w-full object-cover object-center lg:h-full lg:w-full"
            //               />
            //             </div>
            //             <div className="mt-4 flex justify-between">
            //               <div>
            //                 <h3 className="text-sm text-gray-700">
            //                   <a href={`../pages/product/${product.ean}`}>
            //                     <span
            //                       aria-hidden="true"
            //                       className="absolute inset-0"
            //                     />
            //                     {product.name}
            //                   </a>
            //                 </h3>
            //               </div>
            //               <p className="text-sm font-medium text-gray-900">
            //                 {product.price}
            //               </p>
            //               <button onClick={() => handleAddToCart(product)}>
            //                 Add item to cart
            //               </button>
            //             </div>
            //           </div>
            //         ))
            //       ) : (
            //         <div>Nada</div>
            //       )}
            //     </div>
            //   </div>
            // </div>
          )}
        </div>
      </main>
    </>
  );
}
